### ISSUE TITLE
Null valued expression

### ISSUE THREAD

**Issue by Meatballs1** [HarmJ0y/PowerUp#2]
Hitting this issue:

```
PS C:\Windows\system32> Invoke-AllChecks
You cannot call a method on a null-valued expression.
At line:40 char:49
+     $VulnServices = gwmi win32_service | where {$_.pathname.trim() -ne ""} | whe ...
+                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

Rest of it runs as expected. 

Haven't looked into it!

**Comment by HarmJ0y** [comment]
Sorry this took wayyyyyyy  longer than it should have :( There should now be a check to ensure a service exists for any function that enumerates them, as well as an additional check for any path checks for services.

If there are additional issues, let me know!

**Comment by Meatballs1** [comment]
Cool ta :)
